name: OOUIL2
version: '1.0'
main: yaboichips.oOUIL2.OOUIL2
api-version: '1.21'
commands:
  start:
    description: starts the session
    usage: /<command>
  vote:
    description: vote on what role a player has
    usage: /<command> <player> <role>
  save:
    description: if the saved player dies they do not lose a life
    usage: /<command> <player>
  watch:
    description: you can go into someone else’s POV for 15 seconds
    usage: /<command> <player>
  end:
    description: ends the session
    usage: /<command>
  swap:
    description: swaps 2 players
    usage: /<command> <player> <player>
  scan:
    description: scan a player for there role
    usage: /<command> <player>
  transplant:
    description: transfers a life between players
    usage: /<command> <player> <player>
  checklives:
    description: shows you the amount of lives you have
    usage: /<command>
  gift:
    description: gifts a life to someone
    usage: /<command> <player>
  task:
    description: Check or override your task status.
    usage: /task <status|override>